PATH : 
  relative_data_path: "data/census.csv"
  model_path : "model/dt_model.pkl"
  encoder_path: "model/encoder.pkl"
  lb_path: "model/lb.pkl"
DATA_PROC :
  cat_features: 
    - "workclass"
    - "education"
    - "marital-status"
    - "occupation"
    - "relationship"
    - "race"
    - "sex"
    - "native-country"
  label : "salary"
  test_size : 0.2
MODEL_PARAMS :
  criterion : gini
  n_estimators : 30
  max_depth : 10